################################################################################
#                                                                              #
#                      ....         .°°°°.                                     #
#                     .OO#OOo*°**ooO######Oo*°.                                #
#                      O##OOooooo##############OOOOo**°....                    #
#        .....      .°°o####OOOOoO#########################OOOo*°.             #
#        .*O###OOO##########OOOO#####################OOOOOO#######Oo*°         #
#           .o##############OOOOOOO####################OOOOOOOOOOOO###O*°      #
#             .°oO#############OOOO#####################OOOOOOOO##OOOO####o.   #
#                .°*O###################################OOOOOOOOOO#####OO##Oo  #
#                   O##################################O##OO##OOOOOOO########  #
#               ... o#################################OOOOO####OOOO##OO#####O  #
#                 °.*#######OOO#######################OOOOOO####O####O#######  #
#                  ..O######o°*OO####################OOOO##OO################  #
#                    .*O#####OOO#######################OOO##O########O######O  #
#                       *####################O##############O###############O  #
#                        o##############oo############OO#####################  #
#                        *############O. .O###O#######OO#####################  #
#                        .OO#######OOo   *####O#######OOO#######O############  #
#                      ..    ....°°..   .O#######O#####OO######OOO###########  #
#                     ..          .     .O####################O##OO##########  #
#                                        °###########OO###########O##########  #
#                                         °##########O#OO###################O  #
#                                          *#########OOOOOO##################  #
#                                           o#########OOO##O################O  #
#                                            o#########OOO#OO############OOOO  #
#                                             O##########O#OOOOO#########OOOO  #
#                                             °O#######OOOO#OOOOO#########OOO  #
#                                              °O#######OOOOOOOOO########OOOO  #
#                                               o#OOO####OOOOOOOO######OOOOOO  #
#                                               O#OO#####OOOOOOOO#####OOOOOOO  #
#   There's no need to ask about that cat.    .O##########OOOOOOO###OOOO#OOOO  #
#                                                                              #
################################################################################

root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
rules:
  no-console: "off"
