const headerWarning =
    "// Note: This file is automatically generated. Changes made here will be overwritten when running build actions.\n";

export default {
    "output": {
        "banner": headerWarning,
        "file": "dist/archipelago.cjs",
        "format": "cjs",
    },
};
