const headerWarning =
    "// Note: This file is automatically generated. Changes made here will be overwritten when running build actions.\n" +
    "//       Do not proceed unless you know what you're doing.\n";

export default {
    "output": {
        "banner": headerWarning,
        "file": "build/archipelago.cjs",
        "format": "cjs"
    }
};
